# Generated by Django 3.0.7 on 2020-11-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0003_auto_20201122_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
